# Generated by Django 6.0.5 on 2026-05-27 18:18

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_stream',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('quote', 3), ('video', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Titre de section'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote', 'image', 'embed'], 'icon': 'pilcrow', 'label': 'Paragraphe riche'}), 2: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Image'}), 3: ('wagtail.blocks.BlockQuoteBlock', (), {'icon': 'openquote', 'label': 'Citation'}), 4: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'Vidéo (YouTube, Vimeo, etc.)'})}, help_text='Contenu éditorial riche via Wagtail (texte, images, vidéos intégrées).', null=True),
        ),
    ]
