# Generated by Django 6.0.5 on 2026-05-27 23:51

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_content_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_stream',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('image', 2), ('image_text', 7), ('quote', 8), ('video', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'label': 'Titre de section (H2)', 'template': 'blog/blocks/heading_block.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['h2', 'h3', 'bold', 'italic', 'link', 'ol', 'ul', 'hr', 'blockquote', 'image', 'embed'], 'icon': 'pilcrow', 'label': 'Paragraphe riche'}), 2: ('wagtail.images.blocks.ImageBlock', [], {'label': 'Image'}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul', 'blockquote']}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('right', 'Image à droite'), ('left', 'Image à gauche')]}), 6: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('sm', 'Petite'), ('md', 'Moyenne'), ('lg', 'Grande')], 'help_text': "Taille visuelle de l'image dans la mise en page 2 colonnes."}), 7: ('wagtail.blocks.StructBlock', [[('text', 3), ('image', 4), ('image_position', 5), ('image_size', 6)]], {'icon': 'image', 'label': 'Texte + image (2 colonnes)', 'template': 'blog/blocks/image_text_block.html'}), 8: ('wagtail.blocks.BlockQuoteBlock', (), {'icon': 'openquote', 'label': 'Citation'}), 9: ('wagtail.embeds.blocks.EmbedBlock', (), {'icon': 'media', 'label': 'Vidéo (YouTube, Vimeo, etc.)'})}, help_text='Contenu éditorial riche via Wagtail (texte, images, vidéos intégrées).', null=True),
        ),
    ]
