# Generated by Django 6.0.8 on 2026-10-02 12:09

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


def forwards_status_and_cover(apps, schema_editor):
    Article = apps.get_model("blog", "Article")
    Image = apps.get_model("wagtailimages", "Image")
    Collection = apps.get_model("wagtailcore", "Collection")
    root = Collection.objects.filter(depth=1).first()

    for article in Article.objects.all():
        is_live = article.status == "published"
        article.live = is_live
        article.has_unpublished_changes = False
        if is_live:
            article.first_published_at = article.published_at
            article.last_published_at = article.published_at

        if article.cover_image and not article.cover_id and root is not None:
            try:
                from django.core.files.storage import default_storage
                from PIL import Image as PILImage

                name = article.cover_image.name
                with default_storage.open(name, "rb") as fh:
                    with PILImage.open(fh) as im:
                        width, height = im.size
                img = Image.objects.create(
                    title=f"Couverture - {article.title}"[:255],
                    file=name,
                    width=width,
                    height=height,
                    file_size=default_storage.size(name),
                    collection=root,
                )
                article.cover_id = img.pk
            except Exception as exc:  # fichier absent : on garde le repli cover_image
                print(f"  [cover] conversion ignorée pour '{article.title}': {exc}")
        article.save()


def backwards_status(apps, schema_editor):
    Article = apps.get_model("blog", "Article")
    for article in Article.objects.all():
        article.status = "published" if article.live else "draft"
        article.save(update_fields=["status"])


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_article_view_count"),
        ("wagtailcore", "0097_baselogentry_uuid_action_timestamp_indexes"),
        ("wagtailimages", "0027_image_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticleView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visitor", models.CharField(db_index=True, max_length=64)),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
            ],
            options={
                "verbose_name": "vue d'article",
                "verbose_name_plural": "vues d'articles",
            },
        ),
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ["-published_at", "-created_at"],
                "verbose_name": "article",
                "verbose_name_plural": "articles",
            },
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="blog_articl_status_8b18ca_idx",
        ),
        migrations.AddField(
            model_name="article",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                help_text="Idéalement au format paysage (au moins 1600 px de large).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Image de couverture",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="expire_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="expiry date/time"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="expired",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="expired"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="first_published_at",
            field=models.DateTimeField(
                blank=True, db_index=True, null=True, verbose_name="first published at"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="go_live_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="go live date/time"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="has_unpublished_changes",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="has unpublished changes"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="last_published_at",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="last published at"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="latest_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="latest revision",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="live",
            field=models.BooleanField(
                default=True, editable=False, verbose_name="live"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="live_revision",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.revision",
                verbose_name="live revision",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="locked",
            field=models.BooleanField(
                default=False, editable=False, verbose_name="locked"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="locked_at",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="locked at"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="locked_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="locked_%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="locked by",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="articles",
                to="blog.category",
                verbose_name="Catégorie",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, default="", editable=False),
        ),
        migrations.AlterField(
            model_name="article",
            name="content_stream",
            field=wagtail.fields.StreamField(
                [
                    ("paragraph", 0),
                    ("figure", 5),
                    ("verse", 9),
                    ("callout", 13),
                    ("timeline", 20),
                    ("key_points", 24),
                    ("image_text", 29),
                    ("quote", 30),
                    ("video", 31),
                    ("heading", 32),
                    ("image", 33),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "h2",
                                "h3",
                                "h4",
                                "bold",
                                "italic",
                                "strikethrough",
                                "superscript",
                                "link",
                                "document-link",
                                "ol",
                                "ul",
                                "blockquote",
                                "hr",
                                "code",
                                "image",
                                "embed",
                            ],
                            "icon": "pilcrow",
                            "label": "Texte",
                        },
                    ),
                    1: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Image"},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Légende", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Crédit / source", "required": False},
                    ),
                    4: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("text", "Largeur du texte"),
                                ("wide", "Large"),
                                ("small", "Petite"),
                            ],
                            "label": "Largeur",
                        },
                    ),
                    5: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 1), ("caption", 2), ("credit", 3), ("width", 4)]],
                        {},
                    ),
                    6: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Texte du verset", "rows": 3},
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Ex. : Proverbes 3:21-22", "label": "Référence"},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "Louis Segond 1910",
                            "label": "Version",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [[("text", 6), ("reference", 7), ("version", 8)]],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("note", "Note"),
                                ("reflexion", "Pour réfléchir"),
                                ("definition", "Définition"),
                                ("attention", "Attention / nuance"),
                                ("retenir", "À retenir"),
                            ],
                            "label": "Type d'encadré",
                        },
                    ),
                    11: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titre (optionnel)", "required": False},
                    ),
                    12: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "superscript",
                            ],
                            "label": "Contenu",
                        },
                    ),
                    13: (
                        "wagtail.blocks.StructBlock",
                        [[("kind", 10), ("title", 11), ("text", 12)]],
                        {},
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Titre de la chronologie", "required": False},
                    ),
                    15: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Ex. : 325, 1054, XVIe siècle",
                            "label": "Date / période",
                        },
                    ),
                    16: ("wagtail.blocks.CharBlock", (), {"label": "Événement"}),
                    17: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {"label": "Description courte", "required": False, "rows": 2},
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [[("date", 15), ("title", 16), ("text", 17)]],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.ListBlock",
                        (18,),
                        {"label": "Événements", "min_num": 1},
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 14), ("events", 19)]],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"default": "En résumé", "label": "Titre"},
                    ),
                    22: ("wagtail.blocks.CharBlock", (), {"label": "Point"}),
                    23: (
                        "wagtail.blocks.ListBlock",
                        (22,),
                        {"label": "Points clés", "min_num": 1},
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 21), ("points", 23)]],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": [
                                "bold",
                                "italic",
                                "link",
                                "ol",
                                "ul",
                                "blockquote",
                            ]
                        },
                    ),
                    26: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    27: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("right", "Image à droite"),
                                ("left", "Image à gauche"),
                            ]
                        },
                    ),
                    28: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("sm", "Petite"),
                                ("md", "Moyenne"),
                                ("lg", "Grande"),
                            ],
                            "help_text": "Taille visuelle de l'image dans la mise en page 2 colonnes.",
                        },
                    ),
                    29: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("text", 25),
                                ("image", 26),
                                ("image_position", 27),
                                ("image_size", 28),
                            ]
                        ],
                        {
                            "icon": "image",
                            "label": "Texte + image (2 colonnes)",
                            "template": "blog/blocks/image_text_block.html",
                        },
                    ),
                    30: (
                        "wagtail.blocks.BlockQuoteBlock",
                        (),
                        {"icon": "openquote", "label": "Citation"},
                    ),
                    31: (
                        "wagtail.embeds.blocks.EmbedBlock",
                        (),
                        {"icon": "media", "label": "Vidéo (YouTube, Vimeo, etc.)"},
                    ),
                    32: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "form_classname": "title",
                            "icon": "title",
                            "label": "Titre de section (ancien bloc)",
                            "template": "blog/blocks/heading_block.html",
                        },
                    ),
                    33: (
                        "wagtail.images.blocks.ImageBlock",
                        [],
                        {"label": "Image simple (ancien bloc)"},
                    ),
                },
                null=True,
                verbose_name="Contenu",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(
                blank=True, editable=False, null=True, upload_to="articles/covers/"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="excerpt",
            field=models.TextField(
                help_text="2 ou 3 phrases. Affiché dans les listes, sur Google et lors des partages WhatsApp.",
                verbose_name="Résumé",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="featured",
            field=models.BooleanField(
                default=False, verbose_name="Mettre en avant sur l'accueil"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Remplie automatiquement à la première publication.",
                null=True,
                verbose_name="Date de publication affichée",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Généré automatiquement depuis le titre. Évitez de le changer après publication.",
                max_length=240,
                unique=True,
                verbose_name="Adresse (slug)",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="sources",
            field=models.TextField(
                blank=True,
                help_text="Une source par ligne (les liens deviennent cliquables).",
                verbose_name="Sources et références",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="articles", to="blog.tag", verbose_name="Tags"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=220, verbose_name="Titre"),
        ),
        migrations.AlterField(
            model_name="article",
            name="view_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Vues"
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="youtube_url",
            field=models.URLField(blank=True, verbose_name="Vidéo YouTube associée"),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["live", "published_at"], name="blog_articl_live_21e970_idx"
            ),
        ),
        migrations.AddField(
            model_name="articleview",
            name="article",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="views",
                to="blog.article",
            ),
        ),
        migrations.RunPython(forwards_status_and_cover, backwards_status),
        migrations.RemoveField(
            model_name="article",
            name="status",
        ),
        migrations.AddConstraint(
            model_name="articleview",
            constraint=models.UniqueConstraint(
                fields=("article", "visitor"), name="unique_article_visitor"
            ),
        ),
    ]
